// Copyright Pacificao. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "Engine/DataAsset.h"
#include "AgrarianTypes.h"
#include "AgrarianItemDefinitionAsset.generated.h"

UCLASS(BlueprintType)
class UAgrarianItemDefinitionAsset : public UPrimaryDataAsset
{
	GENERATED_BODY()

public:
	UPROPERTY(EditAnywhere, BlueprintReadOnly, Category = "Agrarian|Items")
	FAgrarianItemDefinition Definition;

	UFUNCTION(BlueprintCallable, Category = "Agrarian|Items")
	FAgrarianItemStack MakeStack(int32 Quantity) const;
};
