// Copyright Pacificao. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "AgrarianWeatherExposureZone.generated.h"

class UBoxComponent;

UCLASS(Blueprintable)
class AAgrarianWeatherExposureZone : public AActor
{
	GENERATED_BODY()

public:
	AAgrarianWeatherExposureZone();

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "Agrarian|Weather Exposure")
	TObjectPtr<UBoxComponent> ExposureVolume;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Agrarian|Weather Exposure", meta = (ClampMin = "0", ClampMax = "3"))
	float ExposureMultiplier = 1.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Agrarian|Weather Exposure", meta = (ClampMin = "-20", ClampMax = "20"))
	float TemperatureOffsetC = 0.0f;

	UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = "Agrarian|Weather Exposure")
	FName ExposureZoneId = NAME_None;
};
